// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/definitions/entity.proto

package bsgostuff_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_proto_definitions_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_definitions_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_proto_definitions_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeletableEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletableEntity) Reset() {
	*x = DeletableEntity{}
	mi := &file_proto_definitions_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletableEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletableEntity) ProtoMessage() {}

func (x *DeletableEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_definitions_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletableEntity.ProtoReflect.Descriptor instead.
func (*DeletableEntity) Descriptor() ([]byte, []int) {
	return file_proto_definitions_entity_proto_rawDescGZIP(), []int{1}
}

func (x *DeletableEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeletableEntity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeletableEntity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DeletableEntity) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type UnmodifiedEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmodifiedEntity) Reset() {
	*x = UnmodifiedEntity{}
	mi := &file_proto_definitions_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmodifiedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmodifiedEntity) ProtoMessage() {}

func (x *UnmodifiedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_definitions_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmodifiedEntity.ProtoReflect.Descriptor instead.
func (*UnmodifiedEntity) Descriptor() ([]byte, []int) {
	return file_proto_definitions_entity_proto_rawDescGZIP(), []int{2}
}

func (x *UnmodifiedEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnmodifiedEntity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_definitions_entity_proto protoreflect.FileDescriptor

const file_proto_definitions_entity_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/definitions/entity.proto\x12\tbsgostuff\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb6\x01\n" +
	"\x0fDeletableEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x04 \x01(\bR\tisDeleted\"]\n" +
	"\x10UnmodifiedEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB9Z7github.com/beavernsticks/go-stuff/proto;bsgostuff_protob\x06proto3"

var (
	file_proto_definitions_entity_proto_rawDescOnce sync.Once
	file_proto_definitions_entity_proto_rawDescData []byte
)

func file_proto_definitions_entity_proto_rawDescGZIP() []byte {
	file_proto_definitions_entity_proto_rawDescOnce.Do(func() {
		file_proto_definitions_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_definitions_entity_proto_rawDesc), len(file_proto_definitions_entity_proto_rawDesc)))
	})
	return file_proto_definitions_entity_proto_rawDescData
}

var file_proto_definitions_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_definitions_entity_proto_goTypes = []any{
	(*Entity)(nil),                // 0: bsgostuff.Entity
	(*DeletableEntity)(nil),       // 1: bsgostuff.DeletableEntity
	(*UnmodifiedEntity)(nil),      // 2: bsgostuff.UnmodifiedEntity
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_definitions_entity_proto_depIdxs = []int32{
	3, // 0: bsgostuff.Entity.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: bsgostuff.Entity.updated_at:type_name -> google.protobuf.Timestamp
	3, // 2: bsgostuff.DeletableEntity.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: bsgostuff.DeletableEntity.updated_at:type_name -> google.protobuf.Timestamp
	3, // 4: bsgostuff.UnmodifiedEntity.created_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_definitions_entity_proto_init() }
func file_proto_definitions_entity_proto_init() {
	if File_proto_definitions_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_definitions_entity_proto_rawDesc), len(file_proto_definitions_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_definitions_entity_proto_goTypes,
		DependencyIndexes: file_proto_definitions_entity_proto_depIdxs,
		MessageInfos:      file_proto_definitions_entity_proto_msgTypes,
	}.Build()
	File_proto_definitions_entity_proto = out.File
	file_proto_definitions_entity_proto_goTypes = nil
	file_proto_definitions_entity_proto_depIdxs = nil
}
