// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/definitions/enums.proto

package bsgostuff_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageType int32

const (
	StorageType_STORAGE_TYPE_UNKNOWN StorageType = 0
	StorageType_STORAGE_TYPE_LOCAL   StorageType = 1
	StorageType_STORAGE_TYPE_S3      StorageType = 2
)

// Enum value maps for StorageType.
var (
	StorageType_name = map[int32]string{
		0: "STORAGE_TYPE_UNKNOWN",
		1: "STORAGE_TYPE_LOCAL",
		2: "STORAGE_TYPE_S3",
	}
	StorageType_value = map[string]int32{
		"STORAGE_TYPE_UNKNOWN": 0,
		"STORAGE_TYPE_LOCAL":   1,
		"STORAGE_TYPE_S3":      2,
	}
)

func (x StorageType) Enum() *StorageType {
	p := new(StorageType)
	*p = x
	return p
}

func (x StorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_definitions_enums_proto_enumTypes[0].Descriptor()
}

func (StorageType) Type() protoreflect.EnumType {
	return &file_proto_definitions_enums_proto_enumTypes[0]
}

func (x StorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageType.Descriptor instead.
func (StorageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_definitions_enums_proto_rawDescGZIP(), []int{0}
}

var File_proto_definitions_enums_proto protoreflect.FileDescriptor

const file_proto_definitions_enums_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/definitions/enums.proto\x12\tbsgostuff*T\n" +
	"\vStorageType\x12\x18\n" +
	"\x14STORAGE_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12STORAGE_TYPE_LOCAL\x10\x01\x12\x13\n" +
	"\x0fSTORAGE_TYPE_S3\x10\x02B9Z7github.com/beavernsticks/go-stuff/proto;bsgostuff_protob\x06proto3"

var (
	file_proto_definitions_enums_proto_rawDescOnce sync.Once
	file_proto_definitions_enums_proto_rawDescData []byte
)

func file_proto_definitions_enums_proto_rawDescGZIP() []byte {
	file_proto_definitions_enums_proto_rawDescOnce.Do(func() {
		file_proto_definitions_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_definitions_enums_proto_rawDesc), len(file_proto_definitions_enums_proto_rawDesc)))
	})
	return file_proto_definitions_enums_proto_rawDescData
}

var file_proto_definitions_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_definitions_enums_proto_goTypes = []any{
	(StorageType)(0), // 0: bsgostuff.StorageType
}
var file_proto_definitions_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_definitions_enums_proto_init() }
func file_proto_definitions_enums_proto_init() {
	if File_proto_definitions_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_definitions_enums_proto_rawDesc), len(file_proto_definitions_enums_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_definitions_enums_proto_goTypes,
		DependencyIndexes: file_proto_definitions_enums_proto_depIdxs,
		EnumInfos:         file_proto_definitions_enums_proto_enumTypes,
	}.Build()
	File_proto_definitions_enums_proto = out.File
	file_proto_definitions_enums_proto_goTypes = nil
	file_proto_definitions_enums_proto_depIdxs = nil
}
