// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/definitions/nullable_id.proto

package bsgostuff_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullableID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*NullableID_Id
	//	*NullableID_Null
	Value         isNullableID_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableID) Reset() {
	*x = NullableID{}
	mi := &file_proto_definitions_nullable_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableID) ProtoMessage() {}

func (x *NullableID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_definitions_nullable_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableID.ProtoReflect.Descriptor instead.
func (*NullableID) Descriptor() ([]byte, []int) {
	return file_proto_definitions_nullable_id_proto_rawDescGZIP(), []int{0}
}

func (x *NullableID) GetValue() isNullableID_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NullableID) GetId() string {
	if x != nil {
		if x, ok := x.Value.(*NullableID_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *NullableID) GetNull() bool {
	if x != nil {
		if x, ok := x.Value.(*NullableID_Null); ok {
			return x.Null
		}
	}
	return false
}

type isNullableID_Value interface {
	isNullableID_Value()
}

type NullableID_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type NullableID_Null struct {
	Null bool `protobuf:"varint,2,opt,name=null,proto3,oneof"`
}

func (*NullableID_Id) isNullableID_Value() {}

func (*NullableID_Null) isNullableID_Value() {}

var File_proto_definitions_nullable_id_proto protoreflect.FileDescriptor

const file_proto_definitions_nullable_id_proto_rawDesc = "" +
	"\n" +
	"#proto/definitions/nullable_id.proto\x12\tbsgostuff\"=\n" +
	"\n" +
	"NullableID\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04null\x18\x02 \x01(\bH\x00R\x04nullB\a\n" +
	"\x05valueB9Z7github.com/beavernsticks/go-stuff/proto;bsgostuff_protob\x06proto3"

var (
	file_proto_definitions_nullable_id_proto_rawDescOnce sync.Once
	file_proto_definitions_nullable_id_proto_rawDescData []byte
)

func file_proto_definitions_nullable_id_proto_rawDescGZIP() []byte {
	file_proto_definitions_nullable_id_proto_rawDescOnce.Do(func() {
		file_proto_definitions_nullable_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_definitions_nullable_id_proto_rawDesc), len(file_proto_definitions_nullable_id_proto_rawDesc)))
	})
	return file_proto_definitions_nullable_id_proto_rawDescData
}

var file_proto_definitions_nullable_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_definitions_nullable_id_proto_goTypes = []any{
	(*NullableID)(nil), // 0: bsgostuff.NullableID
}
var file_proto_definitions_nullable_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_definitions_nullable_id_proto_init() }
func file_proto_definitions_nullable_id_proto_init() {
	if File_proto_definitions_nullable_id_proto != nil {
		return
	}
	file_proto_definitions_nullable_id_proto_msgTypes[0].OneofWrappers = []any{
		(*NullableID_Id)(nil),
		(*NullableID_Null)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_definitions_nullable_id_proto_rawDesc), len(file_proto_definitions_nullable_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_definitions_nullable_id_proto_goTypes,
		DependencyIndexes: file_proto_definitions_nullable_id_proto_depIdxs,
		MessageInfos:      file_proto_definitions_nullable_id_proto_msgTypes,
	}.Build()
	File_proto_definitions_nullable_id_proto = out.File
	file_proto_definitions_nullable_id_proto_goTypes = nil
	file_proto_definitions_nullable_id_proto_depIdxs = nil
}
