// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: proto/definitions/page-composer-data.proto

package bsgostuff_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageComposerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *structpb.Struct       `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageComposerData) Reset() {
	*x = PageComposerData{}
	mi := &file_proto_definitions_page_composer_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageComposerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageComposerData) ProtoMessage() {}

func (x *PageComposerData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_definitions_page_composer_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageComposerData.ProtoReflect.Descriptor instead.
func (*PageComposerData) Descriptor() ([]byte, []int) {
	return file_proto_definitions_page_composer_data_proto_rawDescGZIP(), []int{0}
}

func (x *PageComposerData) GetContent() *structpb.Struct {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PageComposerData) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_definitions_page_composer_data_proto protoreflect.FileDescriptor

const file_proto_definitions_page_composer_data_proto_rawDesc = "" +
	"\n" +
	"*proto/definitions/page-composer-data.proto\x12\tbsgostuff\x1a\x1cgoogle/protobuf/struct.proto\"z\n" +
	"\x10PageComposerData\x121\n" +
	"\acontent\x18\x01 \x01(\v2\x17.google.protobuf.StructR\acontent\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadataB9Z7github.com/beavernsticks/go-stuff/proto;bsgostuff_protob\x06proto3"

var (
	file_proto_definitions_page_composer_data_proto_rawDescOnce sync.Once
	file_proto_definitions_page_composer_data_proto_rawDescData []byte
)

func file_proto_definitions_page_composer_data_proto_rawDescGZIP() []byte {
	file_proto_definitions_page_composer_data_proto_rawDescOnce.Do(func() {
		file_proto_definitions_page_composer_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_definitions_page_composer_data_proto_rawDesc), len(file_proto_definitions_page_composer_data_proto_rawDesc)))
	})
	return file_proto_definitions_page_composer_data_proto_rawDescData
}

var file_proto_definitions_page_composer_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_definitions_page_composer_data_proto_goTypes = []any{
	(*PageComposerData)(nil), // 0: bsgostuff.PageComposerData
	(*structpb.Struct)(nil),  // 1: google.protobuf.Struct
}
var file_proto_definitions_page_composer_data_proto_depIdxs = []int32{
	1, // 0: bsgostuff.PageComposerData.content:type_name -> google.protobuf.Struct
	1, // 1: bsgostuff.PageComposerData.metadata:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_definitions_page_composer_data_proto_init() }
func file_proto_definitions_page_composer_data_proto_init() {
	if File_proto_definitions_page_composer_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_definitions_page_composer_data_proto_rawDesc), len(file_proto_definitions_page_composer_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_definitions_page_composer_data_proto_goTypes,
		DependencyIndexes: file_proto_definitions_page_composer_data_proto_depIdxs,
		MessageInfos:      file_proto_definitions_page_composer_data_proto_msgTypes,
	}.Build()
	File_proto_definitions_page_composer_data_proto = out.File
	file_proto_definitions_page_composer_data_proto_goTypes = nil
	file_proto_definitions_page_composer_data_proto_depIdxs = nil
}
