// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: proto/definitions/sort.proto

package bsgostuff_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *string                `protobuf:"bytes,1,opt,name=field,proto3,oneof" json:"field,omitempty"`
	Reverse       *bool                  `protobuf:"varint,2,opt,name=reverse,proto3,oneof" json:"reverse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_proto_definitions_sort_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_definitions_sort_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_proto_definitions_sort_proto_rawDescGZIP(), []int{0}
}

func (x *Sort) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

func (x *Sort) GetReverse() bool {
	if x != nil && x.Reverse != nil {
		return *x.Reverse
	}
	return false
}

var File_proto_definitions_sort_proto protoreflect.FileDescriptor

const file_proto_definitions_sort_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/definitions/sort.proto\x12\tbsgostuff\"V\n" +
	"\x04Sort\x12\x19\n" +
	"\x05field\x18\x01 \x01(\tH\x00R\x05field\x88\x01\x01\x12\x1d\n" +
	"\areverse\x18\x02 \x01(\bH\x01R\areverse\x88\x01\x01B\b\n" +
	"\x06_fieldB\n" +
	"\n" +
	"\b_reverseB9Z7github.com/beavernsticks/go-stuff/proto;bsgostuff_protob\x06proto3"

var (
	file_proto_definitions_sort_proto_rawDescOnce sync.Once
	file_proto_definitions_sort_proto_rawDescData []byte
)

func file_proto_definitions_sort_proto_rawDescGZIP() []byte {
	file_proto_definitions_sort_proto_rawDescOnce.Do(func() {
		file_proto_definitions_sort_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_definitions_sort_proto_rawDesc), len(file_proto_definitions_sort_proto_rawDesc)))
	})
	return file_proto_definitions_sort_proto_rawDescData
}

var file_proto_definitions_sort_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_definitions_sort_proto_goTypes = []any{
	(*Sort)(nil), // 0: bsgostuff.Sort
}
var file_proto_definitions_sort_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_definitions_sort_proto_init() }
func file_proto_definitions_sort_proto_init() {
	if File_proto_definitions_sort_proto != nil {
		return
	}
	file_proto_definitions_sort_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_definitions_sort_proto_rawDesc), len(file_proto_definitions_sort_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_definitions_sort_proto_goTypes,
		DependencyIndexes: file_proto_definitions_sort_proto_depIdxs,
		MessageInfos:      file_proto_definitions_sort_proto_msgTypes,
	}.Build()
	File_proto_definitions_sort_proto = out.File
	file_proto_definitions_sort_proto_goTypes = nil
	file_proto_definitions_sort_proto_depIdxs = nil
}
