// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: events/dlq.proto

package bsgostuff_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeadLetter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalTopic string                 `protobuf:"bytes,1,opt,name=original_topic,json=originalTopic,proto3" json:"original_topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeadLetter) Reset() {
	*x = DeadLetter{}
	mi := &file_events_dlq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetter) ProtoMessage() {}

func (x *DeadLetter) ProtoReflect() protoreflect.Message {
	mi := &file_events_dlq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetter.ProtoReflect.Descriptor instead.
func (*DeadLetter) Descriptor() ([]byte, []int) {
	return file_events_dlq_proto_rawDescGZIP(), []int{0}
}

func (x *DeadLetter) GetOriginalTopic() string {
	if x != nil {
		return x.OriginalTopic
	}
	return ""
}

func (x *DeadLetter) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeadLetter) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeadLetter) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DeadLetter) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_events_dlq_proto protoreflect.FileDescriptor

const file_events_dlq_proto_rawDesc = "" +
	"\n" +
	"\x10events/dlq.proto\x12\x10bsgostuff_events\"\x9b\x01\n" +
	"\n" +
	"DeadLetter\x12%\n" +
	"\x0eoriginal_topic\x18\x01 \x01(\tR\roriginalTopic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestampB;Z9github.com/beavernsticks/go-stuff/events;bsgostuff_eventsb\x06proto3"

var (
	file_events_dlq_proto_rawDescOnce sync.Once
	file_events_dlq_proto_rawDescData []byte
)

func file_events_dlq_proto_rawDescGZIP() []byte {
	file_events_dlq_proto_rawDescOnce.Do(func() {
		file_events_dlq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_dlq_proto_rawDesc), len(file_events_dlq_proto_rawDesc)))
	})
	return file_events_dlq_proto_rawDescData
}

var file_events_dlq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_dlq_proto_goTypes = []any{
	(*DeadLetter)(nil), // 0: bsgostuff_events.DeadLetter
}
var file_events_dlq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_dlq_proto_init() }
func file_events_dlq_proto_init() {
	if File_events_dlq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_dlq_proto_rawDesc), len(file_events_dlq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_dlq_proto_goTypes,
		DependencyIndexes: file_events_dlq_proto_depIdxs,
		MessageInfos:      file_events_dlq_proto_msgTypes,
	}.Build()
	File_events_dlq_proto = out.File
	file_events_dlq_proto_goTypes = nil
	file_events_dlq_proto_depIdxs = nil
}
